### PR TITLE
style: minor formatting updates

### PR DESCRIPTION
**Pull request by educhastenier**
* use `Collections.singletonList` instead of `Arrays.asList`
* fix a typo in javadoc

### CODE REVIEW

**Comment by educhastenier** [comment]
:question: BTW, why isn't there a Copyright header to this file `TransactionLifecycleListener.java`?
I forked this repository and would like to be sure I respect the (LGPL?) license terms.

**Comment by zhfeng** [comment]
run_tests

**Comment by Karm** [comment]
run tests

**Comment by mmusgrov** [comment]
Hello @Karm I still approve of this change. Will you either merge it or withdraw the PR.

**Pull request merged**
