### PR TITLE
JWS-1028 Pass Tx Synchronization Registry to the XA Connection Factory

### PR DESCRIPTION
**Pull request by rsynek**
Ready to merge.

Updated tomcat-dbcp to 9.0.11 which should contain Tom Jenkinson's fixes

### CODE REVIEW

**Comment by rsynek** [comment]
Could please someone review and merge?

**Comment by csutherl** [comment]
@rsynek so this PR works with Tomcat 9.0.11?

**Comment by csutherl** [comment]
Oh, nevermind. I see your initial comments update now :)

**Comment by jfclere** [comment]
we will rebase our JWS5 dbcp tomcat to Tomcat 9.0.11

**Pull request merged**
