### PR TITLE
decouple from the narayana parent

### PR DESCRIPTION
**Pull request by zhfeng**

### CODE REVIEW

**Comment by zhfeng** [comment]
run_tests

**Comment by Karm** [comment]
Run tests

**Comment by Karm** [comment]
@zhfeng It's without the underscore 😄

**Comment by zhfeng** [comment]
Thanks @Karm and it looks like the test fails with
```
<p><b>Root Cause</b></p><pre>java.io.EOFException
	org.postgresql.core.PGStream.receiveChar(PGStream.java:295)
	org.postgresql.core.v3.ConnectionFactoryImpl.doAuthentication(ConnectionFactoryImpl.java:453)
	org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:205)
	org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)
	org.postgresql.jdbc.PgConnection.&lt;init&gt;(PgConnection.java:195)
	org.postgresql.Driver.makeConnection(Driver.java:452)
	org.postgresql.Driver.connect(Driver.java:254)
	java.sql.DriverManager.getConnection(DriverManager.java:664)
	java.sql.DriverManager.getConnection(DriverManager.java:247)
	org.postgresql.ds.common.BaseDataSource.getConnection(BaseDataSource.java:94)
	org.postgresql.xa.PGXADataSource.getXAConnection(PGXADataSource.java:46)
	org.apache.tomcat.dbcp.dbcp2.managed.DataSourceXAConnectionFactory.createConnection(DataSourceXAConnectionFactory.java:151)
```
Is it an issue related to the connection to the pqsql database?

Btw, it is possible to test with the oraclejdk-9 ? I see it does not run in the CI build matrix. I just upgrade the version of the byteman to 4.0.4 by resolving the [JBTM-2992](https://issues.jboss.org/browse/JBTM-2992)

**Comment by Karm** [comment]
@zhfeng Ad DB: weird, gonna check. Ad JDK - > I'll add JDK11 and run with it.  Gonna look at it in half an hour.

**Comment by Karm** [comment]
run tests

**Comment by Karm** [comment]
@zhfeng OpenJDK 8 passes with Tomcat 9.0.11, whereas OpenJDK 11 fails, probably Arquillian passing on Java 11 unfriendly arguments: 
```
INFO: Starting Tomcat with: [/usr/java/jdk-11/bin/java, -Djava.util.logging.config.file=/home/jenkins/jenkins/workspace/narayana-tomcat/903bb326/apache-tomcat-9.0.11/conf/logging.properties, -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager, -Dcom.sun.management.jmxremote.port=8089, -Dcom.sun.management.jmxremote.ssl=false, -Dcom.sun.management.jmxremote.authenticate=false, -Djava.security.egd=file:/dev/./urandom, -Dorg.jboss.byteman.verbose, -Djboss.modules.system.pkgs=org.jboss.byteman, -Dorg.jboss.byteman.transform.all, -javaagent:/home/jenkins/jenkins/workspace/narayana-tomcat/903bb326/tomcat-jta/target/lib/byteman.jar=script:/home/jenkins/jenkins/workspace/narayana-tomcat/903bb326/tomcat-jta/target/test-classes/scripts.btm,listener:true, -classpath, /home/jenkins/jenkins/workspace/narayana-tomcat/903bb326/apache-tomcat-9.0.11/bin/bootstrap.jar:/home/jenkins/jenkins/workspace/narayana-tomcat/903bb326/apache-tomcat-9.0.11/bin/tomcat-juli.jar, -Djava.endorsed.dirs=/home/jenkins/jenkins/workspace/narayana-tomcat/903bb326/apache-tomcat-9.0.11/endorsed, -Dcatalina.base=/home/jenkins/jenkins/workspace/narayana-tomcat/903bb326/apache-tomcat-9.0.11, -Dcatalina.home=/home/jenkins/jenkins/workspace/narayana-tomcat/903bb326/apache-tomcat-9.0.11, -Djava.io.tmpdir=/home/jenkins/jenkins/workspace/narayana-tomcat/903bb326/apache-tomcat-9.0.11/temp, org.apache.catalina.startup.Bootstrap, -config, /home/jenkins/jenkins/workspace/narayana-tomcat/903bb326/apache-tomcat-9.0.11/conf/server.xml, start]
-Djava.endorsed.dirs=/home/jenkins/jenkins/workspace/narayana-tomcat/903bb326/apache-tomcat-9.0.11/endorsed is not supported. Endorsed standards and standalone APIs
in modular form will be supported via the concept of upgradeable modules.
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```

**Comment by zhfeng** [comment]
run tests

**Comment by Karm** [comment]
run tests

**Comment by Karm** [comment]
@zhfeng, I'm sorry, you are neither a member of any of the whitelisted organizations nor an admin on the project. I've corrected that, so as you can also control the bot.

**Comment by Karm** [comment]
Hmm.   run tests

**Comment by zhfeng** [comment]
Thanks @Karm , the https://github.com/arquillian/arquillian-container-tomcat/pull/41 has been merged and we need to upgrade the arquillian-container-tomcat if  they have the new release.

**Comment by Karm** [comment]
@zhfeng O.K. it is weird, Postgres 9.4 with this PR drops connection; Postgres 10 with master suddenly rejects auth:
```
Root Cause
org.postgresql.util.PSQLException: FATAL: password authentication failed for user &quot;narayana_user&quot;
  Location: File: auth.c, Routine: auth_failed, Line: 328
  Server SQLState: 28P01
```
The ```&quot;``` in there is very suspicious. I'll be looking into that now (early today) and possibly add commits to this PR to figure it out.

**Comment by Karm** [comment]
Needless to say it had been working in the past before it broke. But that was before the Jenkins slave upgrade etc. so maybe something went wrong there. Gonna check it out.

**Comment by Karm** [comment]
run tests

**Comment by Karm** [comment]
run tests

Expected failure is *h2*, see [JWS-1126](https://issues.jboss.org/browse/JWS-1126), and there might be a race condition in retrieving DB trace log on Postgres 9.4 ```{"message":"Could not find the file /tmp/db.log in container ...```. The cause of ```password authentication failed for user &quot;narayana_user&quot;``` is not known, but I think it might have been a race condition related to ```PSQLException: the database system is starting up```. The merged #8  should help.

**Comment by Karm** [comment]
JDK 11 keeps failing due to ARQ.  Postgres passes, H2 is a knows issue. I'm merging this and I'll try to fish out the latest ARQ build that has [ARQ-2191](https://issues.jboss.org/browse/ARQ-2191) to get JDK 11 to work.

**Pull request merged**
