### PR TITLE
[JWS-1151] Improving DBCP drivers support with Narayana Tomcat

### PR DESCRIPTION
**Pull request by rsynek**
@rmaucher and @Karm please take a look and let me know if any modifications are needed. Thanks!

### CODE REVIEW

**Comment by Karm** [comment]
run tests

**Comment by rsynek** [comment]
Hi @zhfeng, I added a simple test creating an H2 standalone data source and obtaining a connection from it to illustrate the usage of DataSourceFactory class. Is it sufficient like that?

**Comment by Karm** [comment]
run tests

**Comment by Karm** [comment]
@rsynek 
```
-------------------------------------------------------------------------------
Test set: org.jboss.narayana.tomcat.jta.integration.TestStandaloneDataSource
-------------------------------------------------------------------------------
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.113 s <<< FAILURE! - in org.jboss.narayana.tomcat.jta.integration.TestStandaloneDataSource
testStandaloneDataSourceConnect(org.jboss.narayana.tomcat.jta.integration.TestStandaloneDataSource)  Time elapsed: 0.098 s  <<< ERROR!
java.lang.IllegalStateException: XARecoveryModule is not registered with recovery manager
	at org.jboss.narayana.tomcat.jta.internal.PoolingDataSourceFactory.getXARecoveryModule(PoolingDataSourceFactory.java:166)
	at org.jboss.narayana.tomcat.jta.internal.PoolingDataSourceFactory.createPoolingDataSource(PoolingDataSourceFactory.java:150)
	at org.jboss.narayana.tomcat.jta.integration.utils.internal.PoolingDataSourceWrapperImpl.<init>(PoolingDataSourceWrapperImpl.java:92)
	at org.jboss.narayana.tomcat.jta.integration.utils.DataSourceFactory.setupPoolingDataSource(DataSourceFactory.java:112)
	at org.jboss.narayana.tomcat.jta.integration.utils.DataSourceFactory.setupPoolingDataSource(DataSourceFactory.java:57)
	at org.jboss.narayana.tomcat.jta.integration.TestStandaloneDataSource.testStandaloneDataSourceConnect(TestStandaloneDataSource.java:21)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:273)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:383)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:344)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:125)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:417)

```

**Comment by zhfeng** [comment]
@rsynek The unit test looks good to me and for the CI failure I think it could add some initializing methods in the setUp(). You can find them in the NarayanaJtaServletContextListener. 

Feel free to contact me if you have any problem.

**Comment by rsynek** [comment]
@zhfeng interestingly, I am unable to reproduce the issue locally; running:
`mvn clean integration-test -Parq-tomcat -Dtomcat.user=arquillian -Dtomcat.pass=arquillian -Dtest.db.type=h2`

gives me:

> [INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.639 s - in org.jboss.narayana.tomcat.jta.integration.TestTransactionalDataSourceFactory
> [INFO] Running org.jboss.narayana.tomcat.jta.integration.TestStandaloneDataSource
> [INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 s - in org.jboss.narayana.tomcat.jta.integration.TestStandaloneDataSource

Would you please advice how to run the tests?

**Comment by zhfeng** [comment]
@rsynek OK, it looks like related to the order of the running tests. TestTransactionalDataSourceFactory is running at the first and it has setup the environment.

**Comment by zhfeng** [comment]
I think if you just run with
```
 -Dtest=TestStandaloneDataSource
```
you will see the failure.

**Comment by Karm** [comment]
@rsynek This is what Jenkins job does:
```
...

pushd tools
mvn clean install
popd
# Prepare Maven params
if [[ ${DATABASE_VERSION} =~ .*h2.* ]]; then
    export MAVEN_PARAMS="-Dtest.db.type=h2 "
else if [[ ${DATABASE_VERSION} =~ .*postgres.* ]]; then
    export MAVEN_PARAMS="\
    -Dtest.db.type=container \
    -Dcontainer.database.image=${DATABASE_VERSION} \
    "
else
    echo Unknown database
    echo 1
fi
fi
mvn clean integration-test -Parq-tomcat -Dtomcat.user=arquillian -Dtomcat.pass=arquillian ${MAVEN_PARAMS}
...
```
And as you can see, some tests [intermittently passed](https://ci.modcluster.io/job/narayana-tomcat/64/)...   I guess it is really the execution order.

**Comment by rsynek** [comment]
@Karm @zhfeng thanks, you were right, now I am able to reproduce it locally.

**Comment by rsynek** [comment]
run tests

**Comment by Karm** [comment]
run tests

@rsynek The bot listens only to a whitelist of users. Gonna add you.

**Comment by Karm** [comment]
@rsynek [Works](https://ci.modcluster.io/job/narayana-tomcat/65/DATABASE_VERSION=h2,JDK_VERSION=openjdk-8,TOMCAT_VERSION=9.0.11,label=karm-centos7-x86-64/artifact/tomcat-jta/target/surefire-reports/org.jboss.narayana.tomcat.jta.integration.TestStandaloneDataSource.txt), [Fails](https://ci.modcluster.io/job/narayana-tomcat/65/DATABASE_VERSION=h2,JDK_VERSION=openjdk-8,TOMCAT_VERSION=9.0.11,label=karm-centos7-x86-64/artifact/tomcat-jta/target/surefire-reports/org.jboss.narayana.tomcat.jta.integration.TestTransactionalDataSourceFactory.txt)

**Comment by rsynek** [comment]
run tests

**Comment by rsynek** [comment]
@Karm good to hear. To be honest, I am not particularly happy about this workaround. The root cause is that the RecoveryManager does only partial initialization and termination, so invoking these operations multiple times always result in IllegalStateException to be thrown.

**Comment by rsynek** [comment]
@tomjenkinson thanks Tom, but that probably won't be necessary, I just found out that the NarayanaJtaServletContextListener was not properly initializing the RecoveryManager - see my last commit for more details

**Pull request merged**
